### ISSUE TITLE
Docker is not compatible with Macbooks with M1 chipset processors

### ISSUE THREAD

**Issue by alexandreTrino** [docker/roadmap#192] opened 2021-02-09 00:48 UTC
**Tell us about your request**
Docker needs to be compatible with Macbooks with M1 chipset processors

**Which service(s) is this request for?**
Macbooks

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Docker can not run on Macbooks with M1 chipset processors

**Are you currently working around the issue?**

**Comment by garbuzivan** [comment] 2021-02-09 05:14
> **Tell us about your request**
> Docker needs to be compatible with Macbooks with M1 chipset processors
> 
> **Which service(s) is this request for?**
> Macbooks
> 
> **Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
> Docker can not run on Macbooks with M1 chipset processors
> 
> **Are you currently working around the issue?**

https://docs.docker.com/docker-for-mac/apple-m1/

**Comment by nebuk89** [comment] 2021-02-11 14:37
Closing as a dupe of https://github.com/docker/roadmap/issues/142 

The preview build is out! Please have a go and give us feedback!

**Closed by nebuk89** 2021-02-11 14:37 UTC
Labels: community_new
