### ISSUE TITLE
Implement --network host behaviour like on Linux machines

### ISSUE THREAD

**Issue by alexandertsukanov** [docker/roadmap#365] opened 2022-05-31 10:49 UTC
**Tell us about your request**
According https://docs.docker.com/desktop/mac/networking/ looks like Docker for Mac has some network limitations.

**Which service(s) is this request for?**
Docker for Mac

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It is impossible to bind the container's port to the host machine.

**Are you currently working around the issue?**
Here is a library https://github.com/chipmk/docker-mac-net-connect?ref=golangexample.com which helps to reach the container directly by its IP address. It does half the job but does not resolve the issue with port binding.

**Additional context**
**-p and -P argument** are not an option in my case

**Comment by thaJeztah** [comment] 2023-11-21 00:03
looks like this is a duplicate of https://github.com/docker/roadmap/issues/238

**Closed by thaJeztah** 2023-11-21 00:03 UTC
Labels: community_new
