### ISSUE TITLE
Removing the switch between Linux and Windows containers on Docker Desktop for Windows

### ISSUE THREAD

**Issue by ohault** [docker/roadmap#380] opened 2022-06-21 17:47 UTC
**Tell us about your request**
For Docker Desktop for Windows, the switch between Windows and Linux Containers should be removed on Windows version supporting both type of containers simultaneously.

**Which service(s) is this request for?**
Docker Desktop for Windows

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Single control plane for both Windows and Linux Docker containers on Windows

**Are you currently working around the issue?**
Switching between them is a story of the past.

**Comment by stephen-turner** [comment] 2022-06-24 15:07
Thanks, this is a duplicate of #79. Feel free to go and upvote that one.

**Closed by stephen-turner** 2022-06-24 15:07 UTC
Labels: community_new

**Comment by stephen-turner** [comment] 2022-06-24 16:02
No, it's the same. If you read the original ticket, it says "The option to work streamless with Linux and Windows container is hard, because of the switch context option."
