### ISSUE TITLE
Open dashboard if Docker Desktop app is executed when already running

### ISSUE THREAD

**Issue by xwillq** [docker/roadmap#576] opened 2023-10-18 21:32 UTC
**Tell us about your request**
If docker desktop app is executed when it's already running, it should open dashboard.

**Which service(s) is this request for?**
Docker Desktop for Mac.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I use Spotlight to open apps and windows of hidden apps. With most apps and utilities, if I launch them from Spotlight while they are already running, they open dashboard or configuration window. This eliminates the need to search for their icon in menu bar and allows to hide those icons completely.
Docker Desktop doesn't do this, so I have to search for it in menu bar and click on small menu items.

**Comment by macmirchdocker** [comment] 2023-11-09 16:49
Issue duplicate of:
https://github.com/docker/for-mac/issues/6854

**Comment by macmirchdocker** [comment] 2023-11-09 16:50
Issue duplicate of:
https://github.com/docker/for-mac/issues/6854

**Closed by macmirchdocker** 2023-11-09 16:50 UTC
Labels: community_new, UX
