### ISSUE TITLE
Hide docker desktop menu icon option for MacOS

### ISSUE THREAD

**Issue by parsanoori** [docker/roadmap#420] opened 2022-10-05 22:49 UTC
**Tell us about your request**
Hide docker desktop menu icon option in preferences for MacOS.

**Which service(s) is this request for?**
Docker desktop for MacOS 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Docker desktop  icon over-populating the menu bar whilst there are versions of macbooks which have a notch bar.
On the other another person using one's laptop may accidentally and/or due to unawareness stop the docker engine which is not good. 

**Are you currently working around the issue?**
There's almost no way to maintain this right now.

**Comment by captain-pool** [comment] 2023-01-23 15:28
Facing the same problem. Bumping this up. It's frustrating to not be able to remove the icon.

**Comment by stephen-turner** [comment] 2023-05-22 08:47
This is a dupe of #281.

**Closed by stephen-turner** 2023-05-22 08:47 UTC
Labels: docker_desktop
