### ISSUE TITLE
Add image architecture info as a field for docker images --format

### ISSUE THREAD

**Issue by ericsmalling** [docker/roadmap#525] opened 2023-08-10 13:56 UTC
**Tell us about your request**
I would like to see the architecture of each image in my local cache as a column I can add via the `--format` option on `docker images`

**Which service(s) is this request for?**
docker cli

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I develop on Apple Silicon but usually deploy to intel so have a mix of arch's in my cache at any given time.  This would make it trival to know what arch I'm actually testing with.

**Are you currently working around the issue?**
I have a shell script in my path (named images) that iterates over `docker images` and uses `docker image inspect` to add the column. https://gist.github.com/ericsmalling/d33b2e6a809a697e2bcff820655509c2 
It also highlights any arch's that don't match the host machine.

**Additional context**
The above-mentioned script output looks like this: 
![image](https://github.com/docker/roadmap/assets/361554/95b52542-f651-49aa-8eae-fca503294425)

**Comment by neersighted** [comment] 2023-08-10 15:36
Closing as a duplicate of https://github.com/docker/roadmap/issues/371, as a multi-platform aware API and CLI is implied by the multi-platform content store, and this work is currently in flight.

**Closed** 2023-08-10 16:32 UTC
Labels: community_new
