### ISSUE TITLE
Docker Desktop for Linux

### ISSUE THREAD

**Issue by Daggy1234** [docker/roadmap#154] opened 2020-09-13 13:30 UTC
**Tell us about your request**
Docker desktop to work on linux. I am tired of using kitematic.

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Kitematic is very laggy and buggy. I have used Docker Desktop on windows and would lov eto be able to use it on my main Linux machine.

**Are you currently working around the issue?**
Nope

**Additional context**
Nope

**Comment by ingshtrom** [comment] 2020-09-14 12:50
This is a duplicate of #39 . Please add reactions there to show your support. Thank you!

@nebuk89 Can you close this ticket as it is a duplicate?

**Closed** 2020-09-14 15:16 UTC
Labels: community_new
