### ISSUE TITLE
[Hub] Export Users

### ISSUE THREAD

**Issue by tehautanop** [docker/roadmap#316] opened 2022-02-23 13:59 UTC
Tell us about your request:
As Business license owners, we expect Docker Inc. to provide the tools to export our DockerHub organisation's users data for license management.

Which service(s) is this request for?
DockerHub organisation page(s): 
https://hub.docker.com/orgs/ <DockerOrgId> , 
https://hub.docker.com/orgs/ <DockerOrgId> /teams/company 
and hub-tool

Tell us about the problem you're trying to solve:
Currently the organisation view in https://hub.docker.com/orgs/ <DockerOrgId> - lists all users in your DockerHub organisation, the page shows user email addresses and the content is paginated, which is not very useful for exporting.  

Also, currently the organisation team "company" view in https://hub.docker.com/orgs/ <DockerOrgId> /teams/company - lists all the SSO provisioned users in non-paginated form, however user email addresses are not shown in the page view.

Feature request:
Add option(s) to export DockerHub organisation users data including username/full name/email address as csv, txt or xls. Either from organisation page view or "company" team view.

hub-tool should also include user email addresses as it currently only lists username and full name (if populated, should be automatically populated by SSO.)

**Comment by raj-kumar-j** [comment] 2022-05-13 08:02
@tehautanop If you urgently need an easy way to export user data you can just open dev tools in chome and copy the responses of below urls after visiting `https://hub.docker.com/ors/<your-org>`

`https://hub.docker.com/v2/orgs/<your-org>/members/?page=1&page_size=25&search=altug&type=all`

Just keep incrementing the `page` until you reach the end.

**Comment by josh-higgs** [comment] 2022-08-18 08:18
Hello,
Is there any update on when this might be added? I have recently tried the method that @raj-kumar-j has posted but all I get is "Unauthorized", has this feature been removed?
Thanks.

**Comment by tehautanop** [comment] 2022-08-18 08:20
I wasn't able to export anything using @raj-kumar-j post.
This feature is still in great need.

**Comment by raj-kumar-j** [comment] 2022-08-18 10:51
@tehautanop @josh-higgs I'm fetching the data without any issues. 
```
1. POST  https://hub.docker.com/v2/users/login (post data-> docker admin username and password)
2. Get the token from above and use it as Bearer token in header to get list of users from GET https://hub.docker.com/v2/orgs/<ORG_NAME>/members/?page=1&page_size=25&search=&type=all. 
3. Keep incrementing the page until you reach last page.
```
Try above steps. They should definitely work.

**Comment by nunocoracao** [comment] 2022-08-19 10:10
Hello @tehautanop @josh-higgs we are currently writing the code for this feature. We are tracking progress on https://github.com/docker/roadmap/issues/401. I will mark this as a duplicate. 

Duplicate of https://github.com/docker/roadmap/issues/401

**Comment by nunocoracao** [comment] 2022-08-19 10:10
Duplicate of https://github.com/docker/roadmap/issues/401

**Comment by byjrack** [comment] 2022-09-02 13:46
And as we look at the export can we include the first_login and last_login data?  Another handy metadata point I have been using recently is if the identity is user created, JIT provisioned, or SCIM provisioned.

**Comment by nunocoracao** [comment] 2022-09-06 09:57
Thanks for your suggestion @byjrack, unfortunately, the first iteration of the feature will not include that information. We are looking at how to provide insights in Hub which will include more information on user behavior. cc @ajthilakan

**Closed** 2022-09-22 10:24 UTC
Labels: docker_hub
