### ISSUE TITLE
Allow users to pause Docker Desktop 

### ISSUE THREAD

**Issue by nebuk89** [docker/roadmap#241] opened 2021-07-08 09:13 UTC
**Tell us about your request**
Provide the ability to pause Docker Desktop, rather than shutting down everything instead pause the VM. 
Potentially do this automatically when I unplug my machine to save battery 

**Which service(s) is this request for?**
Docker Desktop 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I don't always want to shut down Desktop but it can take up my battery if I have a lot going on

**Are you currently working around the issue?**
Stopping Docker Desktop 

**Additional context**
N/A

**Comment by justincormack** [comment] 2021-07-13 14:33
Duplicate of #226

**Closed** 2021-07-15 17:07 UTC
Labels: docker_desktop
